name: Push to Docker Registries
on:
  push:
    branches:
      - master
    paths-ignore:
      - README.md

  workflow_dispatch:

env:
  DOCKER_ORG: unfor19
  DOCKER_REPO: awesome-pwa
  DOCKER_BUILD_CONTEXT: awesome-pwa
  # Required secrets:
  # - DOCKERHUB_USERNAME
  # - DOCKERHUB_TOKEN

jobs:
  docker:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        include:
          - DOCKERFILE_PATH: Dockerfile
            DOCKER_BUILD_TARGET: dev
            DOCKER_TAG_ONLY: dev
            NODE_VERSION: 14.17.0
            ALPINE_VERSION: 3.13
          - DOCKERFILE_PATH: Dockerfile
            DOCKER_BUILD_TARGET: app
            DOCKER_TAG_ONLY: app
            NODE_VERSION: 14.17.0
            ALPINE_VERSION: 3.13
    steps:
      - uses: actions/checkout@v2
      - name: Prepare
        id: prepare
        run: |
          set -x
          DOCKER_ORG_REPO="${DOCKER_ORG}/${DOCKER_REPO}"
          echo ::set-output name=docker_org_repo::${DOCKER_ORG_REPO}
          DOCKER_TAG_LATEST=${DOCKER_ORG_REPO}:${{ matrix.DOCKER_TAG_ONLY }}
          echo ::set-output name=docker_tag_latest::${DOCKER_TAG_LATEST}
          DOCKER_TAG_RELEASE=${DOCKER_ORG_REPO}:${{ matrix.DOCKER_TAG_ONLY }}-${GITHUB_SHA:0:8}
          echo ::set-output name=docker_tag_release::${DOCKER_TAG_RELEASE}
          set +x
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@master
        with:
          install: true
      - name: Cache Docker layers
        uses: actions/cache@v2
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-v2-${{ matrix.DOCKER_BUILD_TARGET }}-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-v2-${{ matrix.DOCKER_BUILD_TARGET }}-
      - name: Build Docker Image
        uses: docker/build-push-action@v2
        with:
          context: ${{ env.DOCKER_BUILD_CONTEXT }}
          platforms: linux/amd64
          builder: ${{ steps.buildx.outputs.name }}
          file: ${{ matrix.Dockerfile }}
          build-args: |
            NODE_VERSION=${{ matrix.NODE_VERSION }}
            ALPINE_VERSION=${{ matrix.ALPINE_VERSION }}
          target: ${{ matrix.DOCKER_BUILD_TARGET }}
          push: false
          tags: |
            ${{ steps.prepare.outputs.docker_tag_latest }}
            ${{ steps.prepare.outputs.docker_tag_release }}
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,mode=max,dest=/tmp/.buildx-cache-new
          load: true
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Push to DockerHub
        run: |
          docker image push --all-tags ${{ steps.prepare.outputs.docker_org_repo }}
      - name: Move cache
        run: |
          rm -rf /tmp/.buildx-cache
          mv /tmp/.buildx-cache-new /tmp/.buildx-cache
